# Generated by Django 5.2.7 on 2025-10-09 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster_url', models.URLField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Technology', 'Technology'), ('Food & Drink', 'Food & Drink'), ('Arts & Culture', 'Arts & Culture'), ('Sports', 'Sports'), ('Business', 'Business')], max_length=50)),
                ('host_name', models.CharField(max_length=100)),
                ('payment_methods', models.JSONField(default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
        ),
    ]
